name: speech_to_text_linux
description: Linux implementation of the speech_to_text plugin powered by Vosk and PortAudio.
version: 1.0.0-beta.1
homepage: https://github.com/csdcorp/speech_to_text

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  speech_to_text_platform_interface: ^2.4.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    implements: speech_to_text
    platforms:
      linux:
        pluginClass: SpeechToTextLinuxPlugin
        dartPluginClass: SpeechToTextLinux
